# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml


trigger:
- none

variables:
  containerRegistry: 'AlexRampUpTest'
  imagerepository: 'alexramuptest20230209'
  tag: '$(Build.BuildId)'

stages:
  - stage: Build 
    displayName: Build stage  
    jobs:
    - job: Build
      displayName: Build
      pool:
        vmImage: ubuntu-latest
      steps:

##Use bash to configure DevOps agent
      - task: Bash@3
        inputs:
          filePath: 'EnvironmentSetting/Preinstall_Package.sh'

##Use docker to build image and push into acr
      - task: Docker@2
        displayName: Build and push an image to container registry
        inputs:
          containerRegistry: '$(containerRegistry)'
          repository: '$(imagerepository)'
          command: 'buildAndPush'
          Dockerfile: '**/Dockerfile'
          tags: |
            $(tag)