apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: azure-tls
spec:
  provider: azure
  secretObjects:                            # secretObjects defines the desired state of synced K8s secret objects
  - secretName: ingress-tls-csi
    type: kubernetes.io/tls
    data:
    - objectName: aks-ingress-cert
      key: tls.key
    - objectName: aks-ingress-cert
      key: tls.crt
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"
    userAssignedIdentityID: 3a1ebfb3-8eda-4507-ae69-92504a05a483     # Set the clientID of the user-assigned mandentity to use
    keyvaultName: alexkeyvault1129                 # the name of the AKV instance
    objects: |
      array:
        - |
          objectName: aks-ingress-cert
          objectType: secret
    tenantId: 72f988bf-86f1-41af-91ab-2d7cd011db47                   # the tenant ID of the AKV instance
