apiVersion: v1
kind: Service
metadata:
  labels:
    app: goweb
  name: my-goweb
  namespace: default
spec:
  allocateLoadBalancerNodePorts: true
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - port: 8000
    protocol: TCP
    targetPort: 8000
  selector:
    app: goweb
  sessionAffinity: None
  type: LoadBalancer
